name: vault_storage
description: A package for secure key-value and file storage using Hive and
  flutter_secure_storage.
version: 3.0.1
repository: https://github.com/sgaabdu4/vault_storage

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.29.0"

# Explicit platform support declaration for pub.dev
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  cryptography_plus: ^2.7.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  freerasp: ^7.3.0
  freezed_annotation: ^3.1.0
  hive_ce: ^2.17.0
  hive_ce_flutter: ^2.3.4
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  uuid: ^4.5.2
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.10.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.4
  mocktail: ^1.0.4
